### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by gerc99** [dipien/bye-bye-jetifier#32] opened 2021-03-18 07:16 UTC
```
=========================================
Project: app
=========================================
[WARN] [XmlResourceScanner] No mapping for: android/support/PARENT_ACTIVITY

> Task :canISayByeByeJetifier FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':canISayByeByeJetifier'.
> String index out of range: -2

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at org.objectweb.asm.signature.SignatureReader.parseType(SignatureReader.java:178)
        at org.objectweb.asm.signature.SignatureReader.acceptType(SignatureReader.java:140)
        at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:207)
        at org.objectweb.asm.commons.ClassRemapper.visitField(ClassRemapper.java:171)
        at org.objectweb.asm.ClassReader.readField(ClassReader.java:1104)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:706)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:394)
        at com.dipien.byebyejetifier.scanner.bytecode.BytecodeScanner.scan(BytecodeScanner.kt:21)
        at com.dipien.byebyejetifier.scanner.ScannerProcessor.visit(ScannerProcessor.kt:39)
        at com.dipien.byebyejetifier.archive.ArchiveFile.accept(ArchiveFile.kt:26)
        at com.dipien.byebyejetifier.scanner.ScannerProcessor.visit(ScannerProcessor.kt:21)

```

**Comment by maxirosson** [comment] 2021-03-23 22:58
Thanks for reporting the bug. Do you have a way to reproduce it? For example, the minimum dependencies needed to make the task fail.

**Comment by maxirosson** [comment] 2021-05-01 11:16
Hi, @gerc99. Do you have a way to reproduce it? For example, the minimum dependencies needed to make the task fail.

**Comment by maxirosson** [comment] 2021-05-24 19:40
Closing this issue, because there is no way to reproduce.

**Closed by maxirosson** 2021-05-24 19:40 UTC
Labels: bug
